version: "3"

services:
  travel-plan-automated-builder:
    build: .
    image: travel-plan-automated-builder
    container_name: travel-plan-automated-builder
    ports:
      - "8003:8003"
    volumes:
      - ./log:/log

  neo4j:
    image: neo4j:4.0.4
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_connector_bolt_advertised__address=:7687
      - NEO4J_dbms_memory_heap_initial__size=1024m
      - NEO4J_dbms_memory_heap_max__size=1024m
      - NEO4J_dbms_memory_pagecache_size=256m
      - NEO4JLABS_PLUGINS=["graph-data-science"]