server:
  port: 8003


logging:
  file:
    name: ./log/travel-plan-builder.log
spring:
  data:
    neo4j:
      username: neo4j
      password: neo4j
      uri: bolt://localhost:7687
  application:
    name: microservicecloud-travel-builder
    setting:
      dayDuration: 8
      hrsPastMidnight: 8
      timeZone: Asia/Shanghai
      dateFormat: dd/MM/yyyy HH:mm

info:
  app.name: gof-microservicecloud
  company.name: www.gof.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

eureka:
  client: #client register into eureka
    service-url:
      defaultZone: http://eureka.local:7001/eureka/
  instance:
    instance-id: microservicecloud-travel-builder8003
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: headers
        url: travel-plan-api.local:8001
        value: microservicecloud-travel-plan

