server:
  port: 8003


logging:
  file:
    name: ./log/travel-plan-builder.log
spring:
  data:
    neo4j:
      username: neo4j
      password: neo4j
      uri: bolt://neo4j:7687
  application:
    name: microservicecloud-travel-builder
    setting:
      dayduration: 8
      hrsPastMidnight: 8
      timeZone: Asia/Shanghai
      dateFormat: dd/MM/yyyy HH:mm

info:
  app.name: gof-microservicecloud
  company.name: www.gof.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
