server:
  port: 8002

logging:
  file:
    name: ./log/travel-plan-builder.log
spring:
  application:
    name: microservicecloud-travel-builder

eureka:
  client: #client register into eureka
    service-url:
      defaultZone: http://eureka1:7001/eureka/
  instance:
    instance-id: microservicecloud-travel-builder8002
    prefer-ip-address: true

info:
  app.name: gof-microservicecloud
  company.name: www.gof.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
