server:
  port: 8002

logging:
  file:
    name: ./log/travel-plan-builder.log
spring:
  application:
    name: microservicecloud-travel-builder



info:
  app.name: gof-microservicecloud
  company.name: www.gof.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
